[book]
authors = ["Kevin Sullivan"]
language = "en"
multilingual = false
src = "src"
title = "Discrete Mathematics via Type Theory"


[output.html]
additional-css = ["alectryon.css", "pygments.css"]
additional-js = ["alectryon.js"]

[output.html.fold]
enable = true
level = 0

[output.html.playground.boring-prefixes]
lean = "# "
